# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='phone_number',
        ),
    ]
