# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160405_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate',
            name='credit_card_number',
            field=models.CharField(max_length=300),
        ),
    ]
