# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=300)),
                ('Last_Name', models.CharField(max_length=300)),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Zip_Code', models.CharField(max_length=300)),
                ('Phone_Number', models.CharField(max_length=300)),
                ('credit_card_number', models.CharField(max_length=300)),
                ('expiration_date', models.CharField(max_length=300)),
                ('card_cvv', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='card_cvv',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='cardholders_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='credit_card_number',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='expiration_date',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
