# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160412_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=300)),
                ('Last_Name', models.CharField(max_length=300)),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Zip_Code', models.CharField(max_length=300)),
                ('Phone_Number', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='Email',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
