# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160415_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='visibility',
            new_name='Activity',
        ),
    ]
