# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160421_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerwaiver',
            name='waiver',
            field=models.BooleanField(verbose_name='I hereby accept the waiver.'),
        ),
    ]
