# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160421_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Last_Name',
        ),
        migrations.AlterField(
            model_name='register',
            name='Waiver',
            field=models.CharField(max_length=300),
        ),
    ]
