# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160421_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='amount',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
